steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/helloworld:$COMMIT_SHA', '.' ]
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/helloworld:$COMMIT_SHA']
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'jenkinslearn', '--image', 'gcr.io/$PROJECT_ID/helloworld:$COMMIT_SHA', '--region', 'northamerica-northeast1', '--platform', 'managed']
images:
- gcr.io/$PROJECT_ID/helloworld:$COMMIT_SHA

